export const CREATE_KEYS = "CREATE_KEYS";
export const CREATE_KEYS_SUCCESS = "CREATE_KEYS_SUCCESS";
export const CREATE_KUWA_ID = "CREATE_KUWA_ID";
export const REQUEST_SPONSORSHIP = "REQUEST_SPONSORSHIP";
export const UPLOAD_TO_STORAGE = "UPLOAD_TO_STORAGE";
export const UNLOCK_KUWA_ID = "UNLOCK_KUWA_ID";
export const BACK = "BACK";

//Screen
export const TOGGLE_COLLAPSE = "TOGGLE_COLLAPSE";
export const TOGGLE_PASSWORD_VISIBILITY = "TOGGLE_PASSWORD_VISIBILITY";